scripts/download_pdb.py
This will prevent us from fetching sequences which are all N from PDB. RNAcentral requires no more than 10% N's, this was not previously enforced but is with this change. A quick test shows this excludes 5 chains currently.
=> Add constraint on percent N from PDB (#219)

luigi/rnacentral_entry.py
We must reject sequences if the fraction of N's is over 10%. This adds the required logic to the RNAcentralEntry object.
=> Detect if there are too many N's

luigi/databases/data.py, luigi/mgi.py, luigi/tasks/__init__.py, luigi/tasks/mgi/__init__.py, luigi/tasks/mgi/as_json.py, luigi/tasks/mgi/download.py, luigi/tasks/mgi/rpt_to_csv.py
This adds some simple logic for fetching the MGI data. I would prefer to keep as much import code in the import pipeline. So this contains three major additions. 
First, this can download the MGI data file we can import. This gets saved locally for other things to process.
Secondly, this can parse the downloaded MGI data file to produce a JSON file for the mapping and importing scripts in the webcode to work with. This will parse the data into an Entry object which is normally used to populate the CSV's we import. The advantage of this is that if we do all importing here this will make it much easier as we will have a constant set of objects to work with. I also wanted to keep the logic like inferring RNA type, which this must do, in one place. 
The final thing that this can do is produce …
=> Fetch mgi data

luigi/databases/ensembl/parsers.py, luigi/tests/ensembl/parsers/generic_test.py
This is something Anton and I discussed a while ago. We do not lose data
doing this as we still have gene id in the optional_id. I know this was
an improvement we wanted, but the gain is unclear right now.
We should really do a better job keep data stored in a consistent and 
clear way.
=> Store ensembl locus in gene

data/rfam-duplicates.json, luigi/databases/rfam/helpers.py, luigi/tests/databases/rfam/helpers_test.py, luigi/tests/databases/rfam/parser_test.py
Some entries can have a duplicate accession because I created the
accessions incorrectly. Basically we sort the start, stop when we
shouldn't for some Rfam entries. This fixes that and provides a test
case where two entries have exactly the same start/stop but in different
directions.
=> Fix issue creating duplicate accessions

luigi/databases/ensembl/helpers/ensembl.py, luigi/tests/databases/ensembl/parsers/generic_test.py, luigi/tests/databases/ensembl/utils.py
When building a description using the locus_tag we would add None if
there was no locus_tag. This is not ideal and now prevented. Additionally
there is a test to ensure that no longer happens.
=> Prevent adding 'None' to Ensembl descriptions

data/export/search/URS000000079A_87230.xml, luigi/rnacentral/search/data.py, luigi/rnacentral/search/exporter.py, luigi/tests/rnacentral/search/exporter_test.py
This is the first pass at allowing indexing of QuickGO annotations. One import thing to note is that I haven't check the performance yet.
Here is an example of some data and then the search terms that will be added:
```
RNAcentral      URS0000604143_559292    enables GO:0005515      PMID:11433018   ECO:0000353     UniProtKB:P32495                20180412        UniProt         go_evidence=IPI
RNAcentral      URS0000604143_559292    enables GO:0030559      PMID:9182768    ECO:0000315                     20060911        SGD             go_evidence=IMP
RNAcentral      URS0000604143_559292    involved_in     GO:0031118      PMID:9182768    ECO:0000315                     20060911        SGD             go_evidence=IMP
RNAcentral      URS0000604143_559292    part_of GO:0005730 …
```
=> Search index go terms

luigi/rnacentral/export/ftp/id_mapping.py
Fixes the issue a user found in our ID mapping. We set the RNA type to ncRNA when it was not a standard INSDC RNA type. Additionally, we now use the RNA type we compute and not the RNA type we are given.
=> Fix id export bug

luigi/rnacentral/export/ftp/go_terms.py, luigi/tasks/config.py, luigi/tasks/export/ftp/__init__.py, luigi/tasks/export/ftp/go_annotations.py
This adds an initial GO term export and makes a change to our database. The query to export GO terms is pretty simple and runs in one chunk in ~90 minutes. As this is a first pass I haven't tried to chunk it yet to produce several files.
However, the change to the database is more important. Basically what I have done is create a table for the quality checks `qa_status`. This is much much easier to query and work with I think. The table looks like:
```sql
CREATE TABLE rnacen.qa_status (
rna_id varchar(50) NOT NULL,
upi varchar(30) NULL,
taxid int4 NOT NULL,
has_issue bool NOT NULL,
incomplete_sequence bool NOT NULL,
possible_contamination bool NOT NULL,
missing_rfam_match bool NOT NULL,
CONSTRAINT qa_status_pkey PRIMARY KEY (rna_id),
CONSTRAINT qa_status_upi_fkey FOREIGN KEY (upi) …
```
=> Export rfam go annotations

luigi/rnacentral/search/data.py, luigi/rnacentral/search/exporter.py, luigi/rnacentral/utils.py, luigi/tests/rnacentral/search/exporter_test.py, luigi/tests/rnacentral/utils_test.py, requirements.txt
This changes the search export logic so that we now have a stream based export. Previously we had to generate the entire list of all entries to write. Now we do not generate the entire list in memory and instead just iterate over results. This doesn't look like it improves run time greatly (though I didn't check much), but it does a great job at cutting memory usage down from from ~70G to ~70M. The export still validates according to the schema so everything should be fine.
=> Stream based search export

files/ftp-export/go_annotations/rnacentral_rfam_annotations.sql, ftp-export.nf, rnacentral_pipeline/__main__.py, rnacentral_pipeline/rnacentral/ftp_export/go_terms.py
Fix an issue with not calling the go term export code. Along the way I made it easier to debug as well as moved to the JSON based query output. I prefer that style as it is easier to work with downstream.
=> Fix go term export

.pre-commit-config.yaml, Makefile, config/cluster.config, config/precompute.config, containers/cpat/Dockerfile, files/ftp-export/ensembl/schema.json, files/import-data/expressionatlas/lookup-dump-query.sql, files/search-export/parts/text-mining.sql, poetry.lock, prepare-environment.nf, rnacentral_pipeline/databases/data/databases.py, rnacentral_pipeline/databases/data/entry.py, rnacentral_pipeline/databases/expressionatlas/helpers.py, rnacentral_pipeline/databases/rfam/helpers.py, rnacentral_pipeline/rnacentral/ftp_export/ensembl.py, rnacentral_pipeline/rnacentral/precompute/description/species_specific.py, utils/search-export/src/sequences/normalized.rs, utils/search-export/src/sequences/publication_counts.rs, utils/search-export/src/sequences/raw.rs, workflows/databases/ensembl.nf, workflows/databases/expressionatlas.nf, workflows/export/text-search.nf, workflows/r2dt.nf, workflows/rfam-scan.nf
All changes from codon required to get release 21 through.
Missing from this (because they will be added/fixed in future commits):
- filtering obsolete GO terms
- Exclusion of problematic ensembl entries 
- Skipping long-running genome mapping jobs
- Some database workarounds
=> R21 postrelease patching

files/search-export/parts/accessions.sql
Fixes https://github.com/RNAcentral/rnacentral-webcode/issues/75. I'm fairly certain the issue with weird common names stems from the parsing that is used to build the rnc_accessions table. For some databases (probably only ENA) we parse the names we are given to extract a common name. This is unreliable. But we don't need to fix that (if it is even possible), because we have a better source taxonomy information, rnc_taxonomy. That table is based of the NCBI taxonomy and uses the official names for species, no need for parsing to extract common names. Thus, we stop using the common_name from rnc_accessions and just use the one from rnc_taxonomy.
What this does not change is the usage of the species or lineage from the rnc_accessions table. This should be done, eventually, but before that …
=> Do not use common names from rnc_accessions

files/import-data/load/accessions.ctl, rnacentral_pipeline/databases/data/entry.py
This change writes the URL, if any, to the URL column which is then loaded and put into rnc_accessions. At the moment that column does not exist in the load_ or final table and so needs to be before this is merged. Additionally, this does not stop writing the URL in the note field to not break things for the upcoming release.
Once this is merged, we need to add the column, defaulting to NULL to accessions and the load_ table. Then the update function needs to be updated. We then should test out using this column instead of however URLs for accessions are calculated now. That can wait until after this release. Future work should move the schema for these tables and function into a controlled location, be it here or the web repo.
=> Write URL to it's own column

files/import-data/post-release/001__regions.sql, files/schema/create_load.sql
This change is to remove the rnc_sequence_regions.providing_databases column. It removes all updating logic for it. However, as an effect of this it has a subtle effect on how we need to fetch and display known coordinates. What this will do is no longer delete inactive coordinates. This is ok because we map coordinates to accessions (via rnc_accession_sequence_region) and track which accessions are active (via xref) so we can always tell which provided coordinates are active.
This means though that we need to be careful when extracting active coordinates as we have to check if the xrefs are active. This is a major change from before where we always assumed all entries in the table are active. I think this is ok, as the reduction in logic will be fine and the databases that provide the …
=> Removes updating the rnc_sequence_regions.providing_databases column

files/ftp-export/genome_coordinates/query.sql, rnacentral_pipeline/rnacentral/ftp_export/coordinates/data.py, rnacentral_pipeline/rnacentral/ftp_export/coordinates/gff3.py, workflows/export/ftp/coordinates.nf
I have added the description field from the rnc_rna_precomputed table to the gff file. This is a simple change but it does not only affect the files used by IGV, since this field will also be present on the FTP server within the genome_coordinates directory.
=> The genome browser pop-up should show the description (RNA-369)

files/ftp-export/rediportal/editing-locations.sql, workflows/export/ftp.nf, workflows/export/ftp/rediportal.nf
This should address the last point in #169 to export URS_taxids for all editing events.
=> Rediportal export

rnacentral_pipeline/rnacentral/ftp_export/gpi.py, tests/rnacentral/ftp_export/gpi_test.py
GPI export had a couple issues. First, we needed to add the requested gene symbols from miRBase, see RNA-347 for information. Secondly, we were not extracting the precursor information from miRBase anymore. This commit fixes both issues. We do not add precursor or symbol for things which are not miRBase, but that is ok I think. Additionally, this ads a couple simple tests.
=> Fix GPI export

bin/litscan-create-xml-metadata.py, bin/litscan-get-statistics.py, bin/litscan-retracted-articles.py, rnacentral_pipeline/cli/ensembl.py, rnacentral_pipeline/databases/europepmc/stream.py, rnacentral_pipeline/databases/evlncrnas/lookup.py, rnacentral_pipeline/databases/evlncrnas/parser.py, rnacentral_pipeline/databases/hgnc/helpers.py, rnacentral_pipeline/databases/mgnify/prepare.py, rnacentral_pipeline/databases/plncdb/parser.py, rnacentral_pipeline/databases/psi_mi/tab.py, rnacentral_pipeline/databases/tmrna/helpers.py, rnacentral_pipeline/rnacentral/genome_mapping/blat.py, rnacentral_pipeline/rnacentral/genome_mapping/igv.py, rnacentral_pipeline/rnacentral/precompute/utils.py, rnacentral_pipeline/rnacentral/r2dt/parser.py, rnacentral_pipeline/rnacentral/search_export/compare.py, rnacentral_pipeline/utils.py
Makes the interventions describe in [intervention issue](https://github.com/RNAcentral/rnacentral-import-pipeline/issues/207).
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
Each intervention was done in a dedicated commit with a message explaining it.
As we discussed, I created first a PR with the minor simple alerts:mline-too-long, unnecessary-pass, and broad-exception-caught.
I hope that the review will be easy.
=> Pylint alerts corrections as part of an intervention experiment 1853

config/databases.config, data/tarbase/tarbase.tsv, pytest.ini, rnacentral_pipeline/cli/tarbase.py, rnacentral_pipeline/databases/tarbase/parser.py, tests/databases/tarbase/test_parse_tsv.py, workflows/databases/tarbase.nf
Tarbase v9 no longer uses the generic json loader, so we need to parse their tsv ourselves. 
This PR uses polars to simplify processing, including using polars to query the database and extract the necessary information (e.g. sequence) to build accessions.
The way I've written this uses SQL queries from python. I don't know if that 's something I should have avoided, but it does work, and fairly fast. The maximum number of queries is probably 8 (2 per file here: https://dianalab.e-ce.uth.gr/tarbasev9/downloads), with the majority being quite small. We would have at most 4 concurrent queries, so I think it will be ok
TODO: nextflow stuff
=> Tarbase update

rnacentral_pipeline/databases/tarbase/parser.py, rnacentral_pipeline/rnacentral/ftp_export/coordinates/data.py
Between releases 23 and 24, a large number of RNAs went missing from our genome coordinate FTP exports. GeneCards reported this for our human coordinates, and gave this table that summarises what went missing:
| Database  | Previous Count | Current Count | Percentage Decrease |
|------------|----------------|---------------|---------------------|
| ENA       | 869,516       | 483,656      | 44%                |
| Rfam      | 47,153        | 7,229        | 84%                |
| PDBe      | 3,387         | 102          | 96%                |
| lncRNAdb  | 222           | 55           | 75%                |
| SRPDB     | 34            | 2            | 94%                |
| CRW       | 173           | 0            | 100%               |
| RiboVision | 76            | 0            | 100% …
=> Find the missing RNAs reported by GeneCArds
